[workspace]
resolver = "3"
members = ["crates/*", "compiler/*", "devtools/*", "vm/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
authors = ["Vito Secona <secona00@gmail.com>"]

[workspace.lints.clippy]
self_named_module_files = "deny"

[workspace.dependencies] # keep-sorted start
belalang_dev_tools = { path = "./devtools/belalang_dev_tools" }
belc = { path = "./compiler/belc" }
belc_ast = { path = "./compiler/belc_ast" }
belc_lexer = { path = "./compiler/belc_lexer" }
belvm = { path = "./vm/belvm" }
belvm_bytecode = { path = "./vm/belvm_bytecode" }
belvm_gc = { path = "./vm/belvm_gc/" }
belvm_macros = { path = "./vm/belvm_macros" }
belvm_std = { path = "./vm/belvm_std" }
bincode = "2.0.1"
clap = "4.5.4"
crc32fast = "1.5.0"
libc = "0.2.177"
proc-macro2 = "1.0"
quote = "1.0"
serde = "1.0.219"
syn = "2.0"
thiserror = "2.0.0"
unicode-ident = "1.0.18"
# keep-sorted end
