[package]
name = "belalang_bytecode"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
bincode.workspace = true
crc32fast.workspace = true
thiserror.workspace = true
serde.workspace = true
